KobayaClanguage/find-the-object-game-v2

- src/app/game/settings/account/change/password/complete/page.tsx
パスワード変更完了画面を実装しました
- Close #37  (Issue番号)
未実装につき、無し
> Issue37 : パスワード変更完了画面実装

- src/app/auth/reset/password/complete/page.tsx
/auth/reset/password/complete画面の実装
- Close #44  (Issue番号)
未実装につき無し
> Issue44: パスワードリセット完了画面

- src/app/game/settings/account/logout/page.tsx
ログアウト画面を実装しました。
/game/settings/account/logout
- Close #29 (Issue番号)
未実装なので無し
> Issue29: ログアウト画面実装

- src/app/auth/reset/password/page.tsx
/auth/reset/password
- Close #50 (Issue番号)
未実装につき無し
> Issue50: パスワード再設定用URL送信画面の実装

- src/app/auth/reset/password/register/page.tsx
パスワード再設定画面実装
- Close #47 (Issue番号)
未実装につき無し
> Issue47 : パスワード再設定画面実装

- src/app/game/settings/account/change/email/page.tsx
メールアドレス変更画面(/game/settings/account/change/email)を実装した。
- Close #27 (Issue番号)
未実装のため、無し
> Issue27: メールアドレス変更画面(/game/settings/account/change/email)

- src/app/game/settings/page.tsx
ゲームの設定画面（設定項目一覧画面）を実装した。
- Close #17 (Issue番号)
未実装のため、無し
> issue17:設定画面

- src/app/game/settings/account/change/email/complete/page.tsx
メールアドレス変更完了画面(/game/settings/account/change/email/complete)を実装した。
- Close #35 (Issue番号)
未実装のため、無し
FigmaのUIを一部変更しました。（FIgma上でコメント追加済み）
変更したUIに合わせて実装を行いました。
> メールアドレス変更完了画面を実装した

- src/app/game/settings/account/delete/page.tsx
パスワード入力ボックスを追加した。
- Close #80  (Issue番号)
- ロジックは未実装
> issue/80 (game/settings/account/delete)

- src/app/game/settings/account/delete/page.tsx
- src/app/game/settings/account/logout/page.tsx
- src/features/auth/auth.ts
- Close #96 
- Close #94 
- Close #89
> Issue/96 : 複合的なバグ修正

- bun.lock
- package-lock.json
- package.json
- src/app/email/page.tsx
- src/app/game/settings/account/change/email/complete/page.tsx
- src/app/game/settings/account/change/email/page.tsx
- src/app/magicLink/page.tsx
- src/features/auth/auth.ts
- src/features/auth/magic-link.tsx
メールアドレス変更機能を実装した。
ユーザーがログインした状態でメールアドレス変更画面にパスワード及び新しいメールアドレスを入力すると新しいメールアドレス宛に確認メールが送信される。確認メールに添付されているURLを開くと、変更処理が確定する。
- Close #67  (Issue番号)
> issue67: メールアドレス変更機能を実装した

- src/app/auth/login/page.tsx
- src/app/auth/register/page.tsx
ログイン画面からのリンク先が違うバグを修正
- Close #91 (Issue番号)
- Close #78 
- 「パスワードをお忘れの方はこちら」ボタンのリンクを修正
- 「新規登録」ボタンのリンクを修正
変更前と変更後でUIの修正はなし。
> Issue/91 & Issue/78 : 二つともログイン画面のリンクURLのミス対応

- src/app/auth/reset/password/page.tsx
- src/app/auth/reset/password/register/page.tsx
- src/app/game/settings/account/change/email/page.tsx
- src/features/auth/auth.ts
- src/features/auth/magic-link.tsx
パスワードリセット機能を実装した。
- Close #69 (Issue番号)
完成時にビルドしたところメールアドレス変更画面にエラーがありました。
pb-15というクラス名が原因だったようで(存在しないクラス名)、pb-16にしたところ治りました。
原因は分かりませんが、ビルドエラーが出たままpushするのは好ましくなかったので、修正しました。
> パスワードリセット機能を実装した

- src/app/auth/register/page.tsx
- src/features/auth/auth.ts
- src/features/game/firestore.tsx
- src/firebase/config.ts
アカウント作成時にFirestore上でゲーム進捗管理をするための設定を行い、アカウント削除時にはそれを削除する機能を実装した。
- Close #103  (Issue番号)
変更なし
> アカウント作成・削除後にゲーム進捗データを作成・削除する機能を実装した

- src/app/auth/reset/password/page.tsx
- src/app/auth/reset/password/register/page.tsx
- src/features/auth/auth.ts
- src/features/auth/magic-link.tsx
- src/features/game/scan.ts
外カメラを使うように設定
- Close #114  (Issue番号)
> Issue/114 : 内カメラへの修正

- src/features/game/scan.ts
- src/features/game/stamp.tsx
- src/features/game/stampData.ts
> スタンプ情報を別ファイルに分割した

- src/features/game/NavigationFooter.tsx
> Issue34 : 画像でボタン要素を表現していたものをlucide-reactのアイコンに修正した

- biome.json
- package.json
- src/app/auth/register/page.tsx
- src/app/auth/register/termsOfUse/page.tsx
- src/app/game/scan/page.tsx
- src/app/game/settings/info/aboutUs/page.tsx
- src/app/game/settings/info/howToPlay/page.tsx
- src/app/game/settings/info/termsOfUse/page.tsx
- src/features/game/settings/info/TermsOfUse.tsx
遊び方画面の実装
- Close #99 (Issue番号)
未実装
動作確認時`bun`を最新版にupdateしておいてください。
自分の動作環境では、`bun -v`でバージョンが1.2.20です。
> Issue99 : 遊び方画面の追加

- .gitignore
- src/app/auth/register/page.tsx
- src/app/auth/register/termsOfUse/page.tsx
- src/app/game/settings/info/termsOfUse/page.tsx
- src/features/auth/auth.ts
- src/features/game/settings/info/TermsOfUse.tsx
アカウント登録時にエラーメッセージを追加しました。
- Close #131 (Issue番号)
> アカウント登録時にエラーメッセージ追加(Issue/131)

- src/app/game/settings/info/howToPlay/page.tsx
「QRコードがデンソーウェーブの登録商標」であることを記載
- Close #136 (Issue番号)
> Issue/136 : 遊び方ページに「QRコードがデンソーウェーブの登録商標であることを記載」

- bun.lock
- package.json
- src/app/page.tsx
- Close #138 (Issue番号)
未実装
TailwindCSSのバージョンを最新版にしたので、動作確認時には`bun i`を実行してください。
> Issue/138 : トップページを実装

- src/app/game/settings/info/howToPlay/page.tsx
- src/features/game/settings/info/howToPlay.tsx
- tailwind.config.ts
遊び方ページ(/game/settings/info/howToPlay)の内容をコンポーネントに切り出した。
- Close #142  (Issue番号)
コンポーネントを切り出したため、フロントエンドのUIに変化はありません。
しかし、確認のためコンポーネントに切り出した後のページを載せておきます。
tailwindCSSの設定を一部変えています。(featuresディレクトリ配下のファイル内ではTailwindCSSのクラス名として認識されない設定になっていたため、コンポーネント切り出しの際に障害になっていたため。)
> Issue/142 : 遊び方ページの内容をコンポーネントに切りだした

- src/app/page.tsx
- src/app/preparation/page.tsx
準備中ページの実装
- Close #144 (Issue番号)
- `/preparation`
未実装
- `/`
- `/preparation`
- `/`
> Issue/144 : 準備中ページの実装
